export const SET_DREKELS = 'SET_DREKELS';
export const SET_CROWNS = 'SET_CROWNS';

export const ADD_TO_INVENTORY = 'ADD_TO_INVENTORY';
export const REMOVE_FROM_INVENTORY = 'REMOVE_FROM_INVENTORY';

export const ADD_TO_CHARACTER = 'ADD_TO_CHARACTER';
export const REMOVE_FROM_CHARACTER = 'REMOVE_FROM_CHARACTER';

export const UPDATE_STATS = 'UPDATE_STATS';
